version: "3"
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  db:
    image: mysql:latest
    restart: always
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ZxCvBnM
    ports:
      - '3306:3306'